//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace UI_wp7.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.Iweb2")]
    public interface Iweb2 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iweb2/StartGame", ReplyAction="http://tempuri.org/Iweb2/StartGameResponse")]
        System.IAsyncResult BeginStartGame(System.AsyncCallback callback, object asyncState);
        
        void EndStartGame(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iweb2/GetCurrentCity", ReplyAction="http://tempuri.org/Iweb2/GetCurrentCityResponse")]
        System.IAsyncResult BeginGetCurrentCity(System.AsyncCallback callback, object asyncState);
        
        string EndGetCurrentCity(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iweb2/GetPossibleCities", ReplyAction="http://tempuri.org/Iweb2/GetPossibleCitiesResponse")]
        System.IAsyncResult BeginGetPossibleCities(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndGetPossibleCities(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iweb2/GetCurrentFamous", ReplyAction="http://tempuri.org/Iweb2/GetCurrentFamousResponse")]
        System.IAsyncResult BeginGetCurrentFamous(string city, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndGetCurrentFamous(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iweb2/GetProbablySuspects", ReplyAction="http://tempuri.org/Iweb2/GetProbablySuspectsResponse")]
        System.IAsyncResult BeginGetProbablySuspects(System.AsyncCallback callback, object asyncState);
        
        string EndGetProbablySuspects(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iweb2/GetClueByFamous", ReplyAction="http://tempuri.org/Iweb2/GetClueByFamousResponse")]
        System.IAsyncResult BeginGetClueByFamous(string Famous, System.AsyncCallback callback, object asyncState);
        
        string EndGetClueByFamous(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iweb2/Travel", ReplyAction="http://tempuri.org/Iweb2/TravelResponse")]
        System.IAsyncResult BeginTravel(string City, System.AsyncCallback callback, object asyncState);
        
        void EndTravel(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Iweb2Channel : UI_wp7.ServiceReference.Iweb2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCurrentCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCurrentCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPossibleCitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPossibleCitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCurrentFamousCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCurrentFamousCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProbablySuspectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProbablySuspectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetClueByFamousCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetClueByFamousCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Iweb2Client : System.ServiceModel.ClientBase<UI_wp7.ServiceReference.Iweb2>, UI_wp7.ServiceReference.Iweb2 {
        
        private BeginOperationDelegate onBeginStartGameDelegate;
        
        private EndOperationDelegate onEndStartGameDelegate;
        
        private System.Threading.SendOrPostCallback onStartGameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCurrentCityDelegate;
        
        private EndOperationDelegate onEndGetCurrentCityDelegate;
        
        private System.Threading.SendOrPostCallback onGetCurrentCityCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPossibleCitiesDelegate;
        
        private EndOperationDelegate onEndGetPossibleCitiesDelegate;
        
        private System.Threading.SendOrPostCallback onGetPossibleCitiesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCurrentFamousDelegate;
        
        private EndOperationDelegate onEndGetCurrentFamousDelegate;
        
        private System.Threading.SendOrPostCallback onGetCurrentFamousCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProbablySuspectsDelegate;
        
        private EndOperationDelegate onEndGetProbablySuspectsDelegate;
        
        private System.Threading.SendOrPostCallback onGetProbablySuspectsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetClueByFamousDelegate;
        
        private EndOperationDelegate onEndGetClueByFamousDelegate;
        
        private System.Threading.SendOrPostCallback onGetClueByFamousCompletedDelegate;
        
        private BeginOperationDelegate onBeginTravelDelegate;
        
        private EndOperationDelegate onEndTravelDelegate;
        
        private System.Threading.SendOrPostCallback onTravelCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Iweb2Client() {
        }
        
        public Iweb2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Iweb2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iweb2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iweb2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> StartGameCompleted;
        
        public event System.EventHandler<GetCurrentCityCompletedEventArgs> GetCurrentCityCompleted;
        
        public event System.EventHandler<GetPossibleCitiesCompletedEventArgs> GetPossibleCitiesCompleted;
        
        public event System.EventHandler<GetCurrentFamousCompletedEventArgs> GetCurrentFamousCompleted;
        
        public event System.EventHandler<GetProbablySuspectsCompletedEventArgs> GetProbablySuspectsCompleted;
        
        public event System.EventHandler<GetClueByFamousCompletedEventArgs> GetClueByFamousCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> TravelCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UI_wp7.ServiceReference.Iweb2.BeginStartGame(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginStartGame(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void UI_wp7.ServiceReference.Iweb2.EndStartGame(System.IAsyncResult result) {
            base.Channel.EndStartGame(result);
        }
        
        private System.IAsyncResult OnBeginStartGame(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((UI_wp7.ServiceReference.Iweb2)(this)).BeginStartGame(callback, asyncState);
        }
        
        private object[] OnEndStartGame(System.IAsyncResult result) {
            ((UI_wp7.ServiceReference.Iweb2)(this)).EndStartGame(result);
            return null;
        }
        
        private void OnStartGameCompleted(object state) {
            if ((this.StartGameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.StartGameCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void StartGameAsync() {
            this.StartGameAsync(null);
        }
        
        public void StartGameAsync(object userState) {
            if ((this.onBeginStartGameDelegate == null)) {
                this.onBeginStartGameDelegate = new BeginOperationDelegate(this.OnBeginStartGame);
            }
            if ((this.onEndStartGameDelegate == null)) {
                this.onEndStartGameDelegate = new EndOperationDelegate(this.OnEndStartGame);
            }
            if ((this.onStartGameCompletedDelegate == null)) {
                this.onStartGameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnStartGameCompleted);
            }
            base.InvokeAsync(this.onBeginStartGameDelegate, null, this.onEndStartGameDelegate, this.onStartGameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UI_wp7.ServiceReference.Iweb2.BeginGetCurrentCity(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCurrentCity(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string UI_wp7.ServiceReference.Iweb2.EndGetCurrentCity(System.IAsyncResult result) {
            return base.Channel.EndGetCurrentCity(result);
        }
        
        private System.IAsyncResult OnBeginGetCurrentCity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((UI_wp7.ServiceReference.Iweb2)(this)).BeginGetCurrentCity(callback, asyncState);
        }
        
        private object[] OnEndGetCurrentCity(System.IAsyncResult result) {
            string retVal = ((UI_wp7.ServiceReference.Iweb2)(this)).EndGetCurrentCity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCurrentCityCompleted(object state) {
            if ((this.GetCurrentCityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCurrentCityCompleted(this, new GetCurrentCityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCurrentCityAsync() {
            this.GetCurrentCityAsync(null);
        }
        
        public void GetCurrentCityAsync(object userState) {
            if ((this.onBeginGetCurrentCityDelegate == null)) {
                this.onBeginGetCurrentCityDelegate = new BeginOperationDelegate(this.OnBeginGetCurrentCity);
            }
            if ((this.onEndGetCurrentCityDelegate == null)) {
                this.onEndGetCurrentCityDelegate = new EndOperationDelegate(this.OnEndGetCurrentCity);
            }
            if ((this.onGetCurrentCityCompletedDelegate == null)) {
                this.onGetCurrentCityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCurrentCityCompleted);
            }
            base.InvokeAsync(this.onBeginGetCurrentCityDelegate, null, this.onEndGetCurrentCityDelegate, this.onGetCurrentCityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UI_wp7.ServiceReference.Iweb2.BeginGetPossibleCities(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPossibleCities(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> UI_wp7.ServiceReference.Iweb2.EndGetPossibleCities(System.IAsyncResult result) {
            return base.Channel.EndGetPossibleCities(result);
        }
        
        private System.IAsyncResult OnBeginGetPossibleCities(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((UI_wp7.ServiceReference.Iweb2)(this)).BeginGetPossibleCities(callback, asyncState);
        }
        
        private object[] OnEndGetPossibleCities(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((UI_wp7.ServiceReference.Iweb2)(this)).EndGetPossibleCities(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPossibleCitiesCompleted(object state) {
            if ((this.GetPossibleCitiesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPossibleCitiesCompleted(this, new GetPossibleCitiesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPossibleCitiesAsync() {
            this.GetPossibleCitiesAsync(null);
        }
        
        public void GetPossibleCitiesAsync(object userState) {
            if ((this.onBeginGetPossibleCitiesDelegate == null)) {
                this.onBeginGetPossibleCitiesDelegate = new BeginOperationDelegate(this.OnBeginGetPossibleCities);
            }
            if ((this.onEndGetPossibleCitiesDelegate == null)) {
                this.onEndGetPossibleCitiesDelegate = new EndOperationDelegate(this.OnEndGetPossibleCities);
            }
            if ((this.onGetPossibleCitiesCompletedDelegate == null)) {
                this.onGetPossibleCitiesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPossibleCitiesCompleted);
            }
            base.InvokeAsync(this.onBeginGetPossibleCitiesDelegate, null, this.onEndGetPossibleCitiesDelegate, this.onGetPossibleCitiesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UI_wp7.ServiceReference.Iweb2.BeginGetCurrentFamous(string city, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCurrentFamous(city, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> UI_wp7.ServiceReference.Iweb2.EndGetCurrentFamous(System.IAsyncResult result) {
            return base.Channel.EndGetCurrentFamous(result);
        }
        
        private System.IAsyncResult OnBeginGetCurrentFamous(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string city = ((string)(inValues[0]));
            return ((UI_wp7.ServiceReference.Iweb2)(this)).BeginGetCurrentFamous(city, callback, asyncState);
        }
        
        private object[] OnEndGetCurrentFamous(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((UI_wp7.ServiceReference.Iweb2)(this)).EndGetCurrentFamous(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCurrentFamousCompleted(object state) {
            if ((this.GetCurrentFamousCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCurrentFamousCompleted(this, new GetCurrentFamousCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCurrentFamousAsync(string city) {
            this.GetCurrentFamousAsync(city, null);
        }
        
        public void GetCurrentFamousAsync(string city, object userState) {
            if ((this.onBeginGetCurrentFamousDelegate == null)) {
                this.onBeginGetCurrentFamousDelegate = new BeginOperationDelegate(this.OnBeginGetCurrentFamous);
            }
            if ((this.onEndGetCurrentFamousDelegate == null)) {
                this.onEndGetCurrentFamousDelegate = new EndOperationDelegate(this.OnEndGetCurrentFamous);
            }
            if ((this.onGetCurrentFamousCompletedDelegate == null)) {
                this.onGetCurrentFamousCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCurrentFamousCompleted);
            }
            base.InvokeAsync(this.onBeginGetCurrentFamousDelegate, new object[] {
                        city}, this.onEndGetCurrentFamousDelegate, this.onGetCurrentFamousCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UI_wp7.ServiceReference.Iweb2.BeginGetProbablySuspects(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProbablySuspects(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string UI_wp7.ServiceReference.Iweb2.EndGetProbablySuspects(System.IAsyncResult result) {
            return base.Channel.EndGetProbablySuspects(result);
        }
        
        private System.IAsyncResult OnBeginGetProbablySuspects(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((UI_wp7.ServiceReference.Iweb2)(this)).BeginGetProbablySuspects(callback, asyncState);
        }
        
        private object[] OnEndGetProbablySuspects(System.IAsyncResult result) {
            string retVal = ((UI_wp7.ServiceReference.Iweb2)(this)).EndGetProbablySuspects(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProbablySuspectsCompleted(object state) {
            if ((this.GetProbablySuspectsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProbablySuspectsCompleted(this, new GetProbablySuspectsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProbablySuspectsAsync() {
            this.GetProbablySuspectsAsync(null);
        }
        
        public void GetProbablySuspectsAsync(object userState) {
            if ((this.onBeginGetProbablySuspectsDelegate == null)) {
                this.onBeginGetProbablySuspectsDelegate = new BeginOperationDelegate(this.OnBeginGetProbablySuspects);
            }
            if ((this.onEndGetProbablySuspectsDelegate == null)) {
                this.onEndGetProbablySuspectsDelegate = new EndOperationDelegate(this.OnEndGetProbablySuspects);
            }
            if ((this.onGetProbablySuspectsCompletedDelegate == null)) {
                this.onGetProbablySuspectsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProbablySuspectsCompleted);
            }
            base.InvokeAsync(this.onBeginGetProbablySuspectsDelegate, null, this.onEndGetProbablySuspectsDelegate, this.onGetProbablySuspectsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UI_wp7.ServiceReference.Iweb2.BeginGetClueByFamous(string Famous, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetClueByFamous(Famous, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string UI_wp7.ServiceReference.Iweb2.EndGetClueByFamous(System.IAsyncResult result) {
            return base.Channel.EndGetClueByFamous(result);
        }
        
        private System.IAsyncResult OnBeginGetClueByFamous(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Famous = ((string)(inValues[0]));
            return ((UI_wp7.ServiceReference.Iweb2)(this)).BeginGetClueByFamous(Famous, callback, asyncState);
        }
        
        private object[] OnEndGetClueByFamous(System.IAsyncResult result) {
            string retVal = ((UI_wp7.ServiceReference.Iweb2)(this)).EndGetClueByFamous(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetClueByFamousCompleted(object state) {
            if ((this.GetClueByFamousCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetClueByFamousCompleted(this, new GetClueByFamousCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetClueByFamousAsync(string Famous) {
            this.GetClueByFamousAsync(Famous, null);
        }
        
        public void GetClueByFamousAsync(string Famous, object userState) {
            if ((this.onBeginGetClueByFamousDelegate == null)) {
                this.onBeginGetClueByFamousDelegate = new BeginOperationDelegate(this.OnBeginGetClueByFamous);
            }
            if ((this.onEndGetClueByFamousDelegate == null)) {
                this.onEndGetClueByFamousDelegate = new EndOperationDelegate(this.OnEndGetClueByFamous);
            }
            if ((this.onGetClueByFamousCompletedDelegate == null)) {
                this.onGetClueByFamousCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetClueByFamousCompleted);
            }
            base.InvokeAsync(this.onBeginGetClueByFamousDelegate, new object[] {
                        Famous}, this.onEndGetClueByFamousDelegate, this.onGetClueByFamousCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult UI_wp7.ServiceReference.Iweb2.BeginTravel(string City, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTravel(City, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void UI_wp7.ServiceReference.Iweb2.EndTravel(System.IAsyncResult result) {
            base.Channel.EndTravel(result);
        }
        
        private System.IAsyncResult OnBeginTravel(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string City = ((string)(inValues[0]));
            return ((UI_wp7.ServiceReference.Iweb2)(this)).BeginTravel(City, callback, asyncState);
        }
        
        private object[] OnEndTravel(System.IAsyncResult result) {
            ((UI_wp7.ServiceReference.Iweb2)(this)).EndTravel(result);
            return null;
        }
        
        private void OnTravelCompleted(object state) {
            if ((this.TravelCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TravelCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TravelAsync(string City) {
            this.TravelAsync(City, null);
        }
        
        public void TravelAsync(string City, object userState) {
            if ((this.onBeginTravelDelegate == null)) {
                this.onBeginTravelDelegate = new BeginOperationDelegate(this.OnBeginTravel);
            }
            if ((this.onEndTravelDelegate == null)) {
                this.onEndTravelDelegate = new EndOperationDelegate(this.OnEndTravel);
            }
            if ((this.onTravelCompletedDelegate == null)) {
                this.onTravelCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTravelCompleted);
            }
            base.InvokeAsync(this.onBeginTravelDelegate, new object[] {
                        City}, this.onEndTravelDelegate, this.onTravelCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override UI_wp7.ServiceReference.Iweb2 CreateChannel() {
            return new Iweb2ClientChannel(this);
        }
        
        private class Iweb2ClientChannel : ChannelBase<UI_wp7.ServiceReference.Iweb2>, UI_wp7.ServiceReference.Iweb2 {
            
            public Iweb2ClientChannel(System.ServiceModel.ClientBase<UI_wp7.ServiceReference.Iweb2> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginStartGame(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("StartGame", _args, callback, asyncState);
                return _result;
            }
            
            public void EndStartGame(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("StartGame", _args, result);
            }
            
            public System.IAsyncResult BeginGetCurrentCity(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetCurrentCity", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetCurrentCity(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetCurrentCity", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetPossibleCities(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetPossibleCities", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndGetPossibleCities(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("GetPossibleCities", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCurrentFamous(string city, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = city;
                System.IAsyncResult _result = base.BeginInvoke("GetCurrentFamous", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndGetCurrentFamous(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("GetCurrentFamous", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetProbablySuspects(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetProbablySuspects", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetProbablySuspects(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetProbablySuspects", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetClueByFamous(string Famous, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Famous;
                System.IAsyncResult _result = base.BeginInvoke("GetClueByFamous", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetClueByFamous(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetClueByFamous", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginTravel(string City, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = City;
                System.IAsyncResult _result = base.BeginInvoke("Travel", _args, callback, asyncState);
                return _result;
            }
            
            public void EndTravel(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Travel", _args, result);
            }
        }
    }
}
