insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Buenos Aires','Argentina', 1, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Rio de Janeiro','Brasil', 2, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Paris','Francia', 3, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Londres','Inglaterra', 4, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Montevideo','Uruguay', 5, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Madrid','España', 6, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Roma','Italia', 7, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('New York','Estados Unidos', 8, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('El Cairo','Egipto', 9, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Sydney','Australia', 10, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Nueva Delhi','India', 11, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Tokio','Japón', 12, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Praga','Republica Checa', 13, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Katmandu','Nepal', 14, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('La Habana','Cuba', 15, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Hong Kong','China', 16, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Berlin','Alemania', 17, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Mexico DF','Mexico', 18, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Pekin','China', 19, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Moscu','Rusia', 20, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Cusco','Perú', 21, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Cape Town','Sudáfrica', 22, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Dubai','Emiratos Árabes Unidos', 23, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Seul','Corea del Sur', 24, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Barcelona','España', 25, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Bangkok','Tailandia', 26, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Auckland','Nueva Zelanda ', 27, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Singapur','Singapur', 28, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Jerusalen','Israel', 29, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Cope','Cope', 30, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Dublin','República de Irlanda', 31, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Marrakech','Marruecos', 32, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, CityNumber, Level_LevelId) values ('Amsterdam','Países Bajos', 33, (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
