insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Buenos Aires','Argentina', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Rio de Janeiro','Brasil', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Paris','Francia', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Londres','Inglaterra', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Montevideo','Uruguay', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Madrid','España', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Roma','Italia', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('New York','Estados Unidos', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('El Cairo','Egipto', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Sydney','Australia', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Nueva Delhi','India', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Tokio','Japón', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Praga','Republica Checa', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Katmandu','Nepal', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('La Habana','Cuba', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Hong Kong','China', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Berlin','Alemania', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Mexico DF','Mexico', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Pekin','China', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Moscu','Rusia', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Cusco','Perú', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Cape Town','Sudáfrica', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Dubai','Emiratos Árabes Unidos', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Seul','Corea del Sur', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Barcelona','España', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Bangkok','Tailandia', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Auckland','Nueva Zelanda ', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Singapur','Singapur', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Jerusalen','Israel', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Cope','Cope', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Dublin','República de Irlanda', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Marrakech','Marruecos', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
insert into [interpooldb].[dbo].[Cities] (CityName, CityCountry, Level_LevelId) values ('Amsterdam','Países Bajos', (Select max(LevelId) FROM [interpooldb].[dbo].[Levels]));
