insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Arjen Robben', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Amsterdam')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Dj Tiesto', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Amsterdam')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Frank Rijkaard', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Amsterdam')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Keith Urban', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Auckland')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Peter Jackson', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Auckland')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Russell Crowe', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Auckland')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Chuan Leekpai', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Bangkok')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Paradorn Srichaphan', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Bangkok')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Thaksin Shinawatra', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Bangkok')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Joan Manuel Serrat', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Barcelona')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Juan Carlos', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Barcelona')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Penelope Cruz', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Barcelona')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Franz Beckenbauer', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Berlin')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Heidi Klum', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Berlin')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Michael Schumacher', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Berlin')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Leo Messi', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Buenos Aires')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Maradona', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Buenos Aires')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Valeria Mazza', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Buenos Aires')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Charlize Theron', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Cape Town')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Nelson Mandela', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Cape Town')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Thabo Mbeki', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Cape Town')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Caroline Wozniacki', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Cope')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Helena Christensen', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Cope')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Lars Von Trier', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Cope')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Alberto Fujimori', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Cusco')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Juan Manuel Vargas', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Cusco')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Mario Vargas Llosa', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Cusco')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Mansour Bin Zayed', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Dubai')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Rashid Bin', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Dubai')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Sulaiman Al Fahim', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Dubai')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Bono', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Dublin')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Enya', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Dublin')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Eoin Colfer', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Dublin')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Ahmed Nazif', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('El Cairo')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Claude Francois', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('El Cairo')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Omar Sharif', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('El Cairo')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Jackie Chan', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Hong Kong')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Jet Li', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Hong Kong')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Yao Ming', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Hong Kong')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Bar Refaeli', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Jerusalen')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Benny Hinn', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Jerusalen')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Ralph Bakshi', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Jerusalen')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Arjun  Kumar', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Katmandu')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Dichen Lachman', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Katmandu')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Mohammad Sharif', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Katmandu')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Fidel Castro', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('La Habana')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Gloria Estefan', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('La Habana')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Vida Guerra', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('La Habana')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('David Beckham', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Londres')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Eric Clapton', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Londres')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Noami Campbell', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Londres')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Enrique Iglesias', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Madrid')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Rafael Nadal', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Madrid')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Rodriguez Zapatero', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Madrid')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Gad Elmaleh', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Marrakech')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Hicham Arazi', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Marrakech')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Mohammed Vi', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Marrakech')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Carlos Santana', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Mexico DF')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Paulina Rubio', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Mexico DF')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Thalia', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Mexico DF')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Diego Forlan', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Montevideo')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Eduardo Galeano', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Montevideo')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Natalia Oreiro', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Montevideo')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Anna Kournikova', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Moscu')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Maria Sharapova', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Moscu')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Vladimir Putin', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Moscu')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Barack Obama', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('New York')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Eminem', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('New York')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Lady Gaga', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('New York')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Aishwarya Rai', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Nueva Delhi')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Salman Khan', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Nueva Delhi')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Sania Mirza', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Nueva Delhi')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Nicolas Sarkozy', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Paris')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Roman Polanski', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Paris')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Zinedine Zidane', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Paris')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Bai Ling', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Pekin')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Hu Jintao', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Pekin')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Yuen Biao', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Pekin')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Martina Navratilova', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Praga')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Milos Forman', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Praga')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Veronica Zemanova', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Praga')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Gisele Bundchen', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Rio De Janeiro')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Pele', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Rio De Janeiro')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Ronaldo', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Rio De Janeiro')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Carla Bruni', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Roma')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Fabio Cannavaro', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Roma')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Silvio Berlusconi', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Roma')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Chan-Wook Park', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Seul')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('James Kyson Lee', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Seul')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Yunjin Kim', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Seul')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Fann Wong', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Singapur')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Jackson Rathbone', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Singapur')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Lee Kuan Yew', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Singapur')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Kylie Minogue', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Sydney')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Mark Webber', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Sydney')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Nicole Kidman', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Sydney')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Junichiro Koizumi', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Tokio')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Koda Kumi', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Tokio')));
insert into [interpooldb].[dbo].[Famous] (FamousName, City_CityId) values ('Miyavi', (Select CityId FROM [interpooldb].[dbo].[Cities] where Lower(CityName) like Lower('Tokio')));
