//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace WP7.ServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataCity", Namespace="http://schemas.datacontract.org/2004/07/InterpoolCloudWebRole.Datatypes")]
    public partial class DataCity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime CurrentDateField;
        
        private double GameTimeField;
        
        private double LeftField;
        
        private string NameCityField;
        
        private string NameFileCityField;
        
        private double TopField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CurrentDate {
            get {
                return this.CurrentDateField;
            }
            set {
                if ((this.CurrentDateField.Equals(value) != true)) {
                    this.CurrentDateField = value;
                    this.RaisePropertyChanged("CurrentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double GameTime {
            get {
                return this.GameTimeField;
            }
            set {
                if ((this.GameTimeField.Equals(value) != true)) {
                    this.GameTimeField = value;
                    this.RaisePropertyChanged("GameTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Left {
            get {
                return this.LeftField;
            }
            set {
                if ((this.LeftField.Equals(value) != true)) {
                    this.LeftField = value;
                    this.RaisePropertyChanged("Left");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameCity {
            get {
                return this.NameCityField;
            }
            set {
                if ((object.ReferenceEquals(this.NameCityField, value) != true)) {
                    this.NameCityField = value;
                    this.RaisePropertyChanged("NameCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameFileCity {
            get {
                return this.NameFileCityField;
            }
            set {
                if ((object.ReferenceEquals(this.NameFileCityField, value) != true)) {
                    this.NameFileCityField = value;
                    this.RaisePropertyChanged("NameFileCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Top {
            get {
                return this.TopField;
            }
            set {
                if ((this.TopField.Equals(value) != true)) {
                    this.TopField = value;
                    this.RaisePropertyChanged("Top");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataFamous", Namespace="http://schemas.datacontract.org/2004/07/InterpoolCloudWebRole.Datatypes")]
    public partial class DataFamous : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string FileFamousField;
        
        private string NameFamousField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileFamous {
            get {
                return this.FileFamousField;
            }
            set {
                if ((object.ReferenceEquals(this.FileFamousField, value) != true)) {
                    this.FileFamousField = value;
                    this.RaisePropertyChanged("FileFamous");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameFamous {
            get {
                return this.NameFamousField;
            }
            set {
                if ((object.ReferenceEquals(this.NameFamousField, value) != true)) {
                    this.NameFamousField = value;
                    this.RaisePropertyChanged("NameFamous");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataFacebookUser", Namespace="http://schemas.datacontract.org/2004/07/InterpoolCloudWebRole.Datatypes")]
    public partial class DataFacebookUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string BirthdayField;
        
        private string CinemaField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string GenderField;
        
        private string HometownField;
        
        private string IdFriendField;
        
        private string LastNameField;
        
        private string MusicField;
        
        private WP7.ServiceReference.OAuthFacebook OAuthField;
        
        private string PictureLinkField;
        
        private string TelevisionField;
        
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthdayField, value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cinema {
            get {
                return this.CinemaField;
            }
            set {
                if ((object.ReferenceEquals(this.CinemaField, value) != true)) {
                    this.CinemaField = value;
                    this.RaisePropertyChanged("Cinema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hometown {
            get {
                return this.HometownField;
            }
            set {
                if ((object.ReferenceEquals(this.HometownField, value) != true)) {
                    this.HometownField = value;
                    this.RaisePropertyChanged("Hometown");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdFriend {
            get {
                return this.IdFriendField;
            }
            set {
                if ((object.ReferenceEquals(this.IdFriendField, value) != true)) {
                    this.IdFriendField = value;
                    this.RaisePropertyChanged("IdFriend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Music {
            get {
                return this.MusicField;
            }
            set {
                if ((object.ReferenceEquals(this.MusicField, value) != true)) {
                    this.MusicField = value;
                    this.RaisePropertyChanged("Music");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WP7.ServiceReference.OAuthFacebook OAuth {
            get {
                return this.OAuthField;
            }
            set {
                if ((object.ReferenceEquals(this.OAuthField, value) != true)) {
                    this.OAuthField = value;
                    this.RaisePropertyChanged("OAuth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PictureLink {
            get {
                return this.PictureLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureLinkField, value) != true)) {
                    this.PictureLinkField = value;
                    this.RaisePropertyChanged("PictureLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Television {
            get {
                return this.TelevisionField;
            }
            set {
                if ((object.ReferenceEquals(this.TelevisionField, value) != true)) {
                    this.TelevisionField = value;
                    this.RaisePropertyChanged("Television");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OAuthFacebook", Namespace="http://schemas.datacontract.org/2004/07/InterpoolCloudWebRole.FacebookCommunicati" +
        "on")]
    public partial class OAuthFacebook : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ConsumerKeyField;
        
        private string ConsumerSecretField;
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerKey {
            get {
                return this.ConsumerKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsumerKeyField, value) != true)) {
                    this.ConsumerKeyField = value;
                    this.RaisePropertyChanged("ConsumerKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumerSecret {
            get {
                return this.ConsumerSecretField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsumerSecretField, value) != true)) {
                    this.ConsumerSecretField = value;
                    this.RaisePropertyChanged("ConsumerSecret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListFacebookUser", Namespace="http://schemas.datacontract.org/2004/07/InterpoolCloudWebRole.Datatypes")]
    public partial class DataListFacebookUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime CurrentDateField;
        
        private System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataFacebookUser> ListFacebookUserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CurrentDate {
            get {
                return this.CurrentDateField;
            }
            set {
                if ((this.CurrentDateField.Equals(value) != true)) {
                    this.CurrentDateField = value;
                    this.RaisePropertyChanged("CurrentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataFacebookUser> ListFacebookUser {
            get {
                return this.ListFacebookUserField;
            }
            set {
                if ((object.ReferenceEquals(this.ListFacebookUserField, value) != true)) {
                    this.ListFacebookUserField = value;
                    this.RaisePropertyChanged("ListFacebookUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataClue", Namespace="http://schemas.datacontract.org/2004/07/InterpoolCloudWebRole.Datatypes")]
    public partial class DataClue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ClueField;
        
        private System.DateTime CurrentDateField;
        
        private WP7.ServiceReference.DataClue.State StatesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clue {
            get {
                return this.ClueField;
            }
            set {
                if ((object.ReferenceEquals(this.ClueField, value) != true)) {
                    this.ClueField = value;
                    this.RaisePropertyChanged("Clue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CurrentDate {
            get {
                return this.CurrentDateField;
            }
            set {
                if ((this.CurrentDateField.Equals(value) != true)) {
                    this.CurrentDateField = value;
                    this.RaisePropertyChanged("CurrentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WP7.ServiceReference.DataClue.State States {
            get {
                return this.StatesField;
            }
            set {
                if ((this.StatesField.Equals(value) != true)) {
                    this.StatesField = value;
                    this.RaisePropertyChanged("States");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="DataClue.State", Namespace="http://schemas.datacontract.org/2004/07/InterpoolCloudWebRole.Datatypes")]
        public enum State : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PL = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            LOSE_NEOA = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            LOSE_EOAW = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            LOSE_TO = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            WIN = 4,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IInterpoolWP7")]
    public interface IInterpoolWP7 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IInterpoolWP7/StartGame", ReplyAction="http://tempuri.org/IInterpoolWP7/StartGameResponse")]
        System.IAsyncResult BeginStartGame(string userIdFacebook, System.AsyncCallback callback, object asyncState);
        
        void EndStartGame(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IInterpoolWP7/GetUserIdFacebook", ReplyAction="http://tempuri.org/IInterpoolWP7/GetUserIdFacebookResponse")]
        System.IAsyncResult BeginGetUserIdFacebook(string idLogin, System.AsyncCallback callback, object asyncState);
        
        string EndGetUserIdFacebook(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IInterpoolWP7/GetCurrentCity", ReplyAction="http://tempuri.org/IInterpoolWP7/GetCurrentCityResponse")]
        System.IAsyncResult BeginGetCurrentCity(string userIdFacebook, System.AsyncCallback callback, object asyncState);
        
        WP7.ServiceReference.DataCity EndGetCurrentCity(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IInterpoolWP7/GetPossibleCities", ReplyAction="http://tempuri.org/IInterpoolWP7/GetPossibleCitiesResponse")]
        System.IAsyncResult BeginGetPossibleCities(string userIdFacebook, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataCity> EndGetPossibleCities(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IInterpoolWP7/GetCurrentFamous", ReplyAction="http://tempuri.org/IInterpoolWP7/GetCurrentFamousResponse")]
        System.IAsyncResult BeginGetCurrentFamous(string userIdFacebook, int numClue, System.AsyncCallback callback, object asyncState);
        
        WP7.ServiceReference.DataFamous EndGetCurrentFamous(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IInterpoolWP7/FilterSuspects", ReplyAction="http://tempuri.org/IInterpoolWP7/FilterSuspectsResponse")]
        System.IAsyncResult BeginFilterSuspects(string userIdFacebook, WP7.ServiceReference.DataFacebookUser fbud, System.AsyncCallback callback, object asyncState);
        
        WP7.ServiceReference.DataListFacebookUser EndFilterSuspects(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IInterpoolWP7/EmitOrderOfArrest", ReplyAction="http://tempuri.org/IInterpoolWP7/EmitOrderOfArrestResponse")]
        System.IAsyncResult BeginEmitOrderOfArrest(string userIdFacebook, string userIdFacebookSuspect, System.AsyncCallback callback, object asyncState);
        
        void EndEmitOrderOfArrest(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IInterpoolWP7/GetCities", ReplyAction="http://tempuri.org/IInterpoolWP7/GetCitiesResponse")]
        System.IAsyncResult BeginGetCities(string userIdFacebook, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataCity> EndGetCities(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IInterpoolWP7/Travel", ReplyAction="http://tempuri.org/IInterpoolWP7/TravelResponse")]
        System.IAsyncResult BeginTravel(string userIdFacebook, string nameNextCity, System.AsyncCallback callback, object asyncState);
        
        WP7.ServiceReference.DataCity EndTravel(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IInterpoolWP7/GetClueByFamous", ReplyAction="http://tempuri.org/IInterpoolWP7/GetClueByFamousResponse")]
        System.IAsyncResult BeginGetClueByFamous(string userIdFacebook, int numFamous, System.AsyncCallback callback, object asyncState);
        
        WP7.ServiceReference.DataClue EndGetClueByFamous(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInterpoolWP7Channel : WP7.ServiceReference.IInterpoolWP7, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserIdFacebookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserIdFacebookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCurrentCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCurrentCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WP7.ServiceReference.DataCity Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WP7.ServiceReference.DataCity)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPossibleCitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPossibleCitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataCity> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataCity>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCurrentFamousCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCurrentFamousCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WP7.ServiceReference.DataFamous Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WP7.ServiceReference.DataFamous)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FilterSuspectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FilterSuspectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WP7.ServiceReference.DataListFacebookUser Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WP7.ServiceReference.DataListFacebookUser)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataCity> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataCity>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TravelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TravelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WP7.ServiceReference.DataCity Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WP7.ServiceReference.DataCity)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetClueByFamousCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetClueByFamousCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WP7.ServiceReference.DataClue Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WP7.ServiceReference.DataClue)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterpoolWP7Client : System.ServiceModel.ClientBase<WP7.ServiceReference.IInterpoolWP7>, WP7.ServiceReference.IInterpoolWP7 {
        
        private BeginOperationDelegate onBeginStartGameDelegate;
        
        private EndOperationDelegate onEndStartGameDelegate;
        
        private System.Threading.SendOrPostCallback onStartGameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserIdFacebookDelegate;
        
        private EndOperationDelegate onEndGetUserIdFacebookDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserIdFacebookCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCurrentCityDelegate;
        
        private EndOperationDelegate onEndGetCurrentCityDelegate;
        
        private System.Threading.SendOrPostCallback onGetCurrentCityCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPossibleCitiesDelegate;
        
        private EndOperationDelegate onEndGetPossibleCitiesDelegate;
        
        private System.Threading.SendOrPostCallback onGetPossibleCitiesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCurrentFamousDelegate;
        
        private EndOperationDelegate onEndGetCurrentFamousDelegate;
        
        private System.Threading.SendOrPostCallback onGetCurrentFamousCompletedDelegate;
        
        private BeginOperationDelegate onBeginFilterSuspectsDelegate;
        
        private EndOperationDelegate onEndFilterSuspectsDelegate;
        
        private System.Threading.SendOrPostCallback onFilterSuspectsCompletedDelegate;
        
        private BeginOperationDelegate onBeginEmitOrderOfArrestDelegate;
        
        private EndOperationDelegate onEndEmitOrderOfArrestDelegate;
        
        private System.Threading.SendOrPostCallback onEmitOrderOfArrestCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCitiesDelegate;
        
        private EndOperationDelegate onEndGetCitiesDelegate;
        
        private System.Threading.SendOrPostCallback onGetCitiesCompletedDelegate;
        
        private BeginOperationDelegate onBeginTravelDelegate;
        
        private EndOperationDelegate onEndTravelDelegate;
        
        private System.Threading.SendOrPostCallback onTravelCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetClueByFamousDelegate;
        
        private EndOperationDelegate onEndGetClueByFamousDelegate;
        
        private System.Threading.SendOrPostCallback onGetClueByFamousCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public InterpoolWP7Client() {
        }
        
        public InterpoolWP7Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterpoolWP7Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterpoolWP7Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterpoolWP7Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> StartGameCompleted;
        
        public event System.EventHandler<GetUserIdFacebookCompletedEventArgs> GetUserIdFacebookCompleted;
        
        public event System.EventHandler<GetCurrentCityCompletedEventArgs> GetCurrentCityCompleted;
        
        public event System.EventHandler<GetPossibleCitiesCompletedEventArgs> GetPossibleCitiesCompleted;
        
        public event System.EventHandler<GetCurrentFamousCompletedEventArgs> GetCurrentFamousCompleted;
        
        public event System.EventHandler<FilterSuspectsCompletedEventArgs> FilterSuspectsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EmitOrderOfArrestCompleted;
        
        public event System.EventHandler<GetCitiesCompletedEventArgs> GetCitiesCompleted;
        
        public event System.EventHandler<TravelCompletedEventArgs> TravelCompleted;
        
        public event System.EventHandler<GetClueByFamousCompletedEventArgs> GetClueByFamousCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7.ServiceReference.IInterpoolWP7.BeginStartGame(string userIdFacebook, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginStartGame(userIdFacebook, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void WP7.ServiceReference.IInterpoolWP7.EndStartGame(System.IAsyncResult result) {
            base.Channel.EndStartGame(result);
        }
        
        private System.IAsyncResult OnBeginStartGame(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userIdFacebook = ((string)(inValues[0]));
            return ((WP7.ServiceReference.IInterpoolWP7)(this)).BeginStartGame(userIdFacebook, callback, asyncState);
        }
        
        private object[] OnEndStartGame(System.IAsyncResult result) {
            ((WP7.ServiceReference.IInterpoolWP7)(this)).EndStartGame(result);
            return null;
        }
        
        private void OnStartGameCompleted(object state) {
            if ((this.StartGameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.StartGameCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void StartGameAsync(string userIdFacebook) {
            this.StartGameAsync(userIdFacebook, null);
        }
        
        public void StartGameAsync(string userIdFacebook, object userState) {
            if ((this.onBeginStartGameDelegate == null)) {
                this.onBeginStartGameDelegate = new BeginOperationDelegate(this.OnBeginStartGame);
            }
            if ((this.onEndStartGameDelegate == null)) {
                this.onEndStartGameDelegate = new EndOperationDelegate(this.OnEndStartGame);
            }
            if ((this.onStartGameCompletedDelegate == null)) {
                this.onStartGameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnStartGameCompleted);
            }
            base.InvokeAsync(this.onBeginStartGameDelegate, new object[] {
                        userIdFacebook}, this.onEndStartGameDelegate, this.onStartGameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7.ServiceReference.IInterpoolWP7.BeginGetUserIdFacebook(string idLogin, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserIdFacebook(idLogin, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string WP7.ServiceReference.IInterpoolWP7.EndGetUserIdFacebook(System.IAsyncResult result) {
            return base.Channel.EndGetUserIdFacebook(result);
        }
        
        private System.IAsyncResult OnBeginGetUserIdFacebook(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string idLogin = ((string)(inValues[0]));
            return ((WP7.ServiceReference.IInterpoolWP7)(this)).BeginGetUserIdFacebook(idLogin, callback, asyncState);
        }
        
        private object[] OnEndGetUserIdFacebook(System.IAsyncResult result) {
            string retVal = ((WP7.ServiceReference.IInterpoolWP7)(this)).EndGetUserIdFacebook(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserIdFacebookCompleted(object state) {
            if ((this.GetUserIdFacebookCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserIdFacebookCompleted(this, new GetUserIdFacebookCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserIdFacebookAsync(string idLogin) {
            this.GetUserIdFacebookAsync(idLogin, null);
        }
        
        public void GetUserIdFacebookAsync(string idLogin, object userState) {
            if ((this.onBeginGetUserIdFacebookDelegate == null)) {
                this.onBeginGetUserIdFacebookDelegate = new BeginOperationDelegate(this.OnBeginGetUserIdFacebook);
            }
            if ((this.onEndGetUserIdFacebookDelegate == null)) {
                this.onEndGetUserIdFacebookDelegate = new EndOperationDelegate(this.OnEndGetUserIdFacebook);
            }
            if ((this.onGetUserIdFacebookCompletedDelegate == null)) {
                this.onGetUserIdFacebookCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserIdFacebookCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserIdFacebookDelegate, new object[] {
                        idLogin}, this.onEndGetUserIdFacebookDelegate, this.onGetUserIdFacebookCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7.ServiceReference.IInterpoolWP7.BeginGetCurrentCity(string userIdFacebook, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCurrentCity(userIdFacebook, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WP7.ServiceReference.DataCity WP7.ServiceReference.IInterpoolWP7.EndGetCurrentCity(System.IAsyncResult result) {
            return base.Channel.EndGetCurrentCity(result);
        }
        
        private System.IAsyncResult OnBeginGetCurrentCity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userIdFacebook = ((string)(inValues[0]));
            return ((WP7.ServiceReference.IInterpoolWP7)(this)).BeginGetCurrentCity(userIdFacebook, callback, asyncState);
        }
        
        private object[] OnEndGetCurrentCity(System.IAsyncResult result) {
            WP7.ServiceReference.DataCity retVal = ((WP7.ServiceReference.IInterpoolWP7)(this)).EndGetCurrentCity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCurrentCityCompleted(object state) {
            if ((this.GetCurrentCityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCurrentCityCompleted(this, new GetCurrentCityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCurrentCityAsync(string userIdFacebook) {
            this.GetCurrentCityAsync(userIdFacebook, null);
        }
        
        public void GetCurrentCityAsync(string userIdFacebook, object userState) {
            if ((this.onBeginGetCurrentCityDelegate == null)) {
                this.onBeginGetCurrentCityDelegate = new BeginOperationDelegate(this.OnBeginGetCurrentCity);
            }
            if ((this.onEndGetCurrentCityDelegate == null)) {
                this.onEndGetCurrentCityDelegate = new EndOperationDelegate(this.OnEndGetCurrentCity);
            }
            if ((this.onGetCurrentCityCompletedDelegate == null)) {
                this.onGetCurrentCityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCurrentCityCompleted);
            }
            base.InvokeAsync(this.onBeginGetCurrentCityDelegate, new object[] {
                        userIdFacebook}, this.onEndGetCurrentCityDelegate, this.onGetCurrentCityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7.ServiceReference.IInterpoolWP7.BeginGetPossibleCities(string userIdFacebook, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPossibleCities(userIdFacebook, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataCity> WP7.ServiceReference.IInterpoolWP7.EndGetPossibleCities(System.IAsyncResult result) {
            return base.Channel.EndGetPossibleCities(result);
        }
        
        private System.IAsyncResult OnBeginGetPossibleCities(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userIdFacebook = ((string)(inValues[0]));
            return ((WP7.ServiceReference.IInterpoolWP7)(this)).BeginGetPossibleCities(userIdFacebook, callback, asyncState);
        }
        
        private object[] OnEndGetPossibleCities(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataCity> retVal = ((WP7.ServiceReference.IInterpoolWP7)(this)).EndGetPossibleCities(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPossibleCitiesCompleted(object state) {
            if ((this.GetPossibleCitiesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPossibleCitiesCompleted(this, new GetPossibleCitiesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPossibleCitiesAsync(string userIdFacebook) {
            this.GetPossibleCitiesAsync(userIdFacebook, null);
        }
        
        public void GetPossibleCitiesAsync(string userIdFacebook, object userState) {
            if ((this.onBeginGetPossibleCitiesDelegate == null)) {
                this.onBeginGetPossibleCitiesDelegate = new BeginOperationDelegate(this.OnBeginGetPossibleCities);
            }
            if ((this.onEndGetPossibleCitiesDelegate == null)) {
                this.onEndGetPossibleCitiesDelegate = new EndOperationDelegate(this.OnEndGetPossibleCities);
            }
            if ((this.onGetPossibleCitiesCompletedDelegate == null)) {
                this.onGetPossibleCitiesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPossibleCitiesCompleted);
            }
            base.InvokeAsync(this.onBeginGetPossibleCitiesDelegate, new object[] {
                        userIdFacebook}, this.onEndGetPossibleCitiesDelegate, this.onGetPossibleCitiesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7.ServiceReference.IInterpoolWP7.BeginGetCurrentFamous(string userIdFacebook, int numClue, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCurrentFamous(userIdFacebook, numClue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WP7.ServiceReference.DataFamous WP7.ServiceReference.IInterpoolWP7.EndGetCurrentFamous(System.IAsyncResult result) {
            return base.Channel.EndGetCurrentFamous(result);
        }
        
        private System.IAsyncResult OnBeginGetCurrentFamous(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userIdFacebook = ((string)(inValues[0]));
            int numClue = ((int)(inValues[1]));
            return ((WP7.ServiceReference.IInterpoolWP7)(this)).BeginGetCurrentFamous(userIdFacebook, numClue, callback, asyncState);
        }
        
        private object[] OnEndGetCurrentFamous(System.IAsyncResult result) {
            WP7.ServiceReference.DataFamous retVal = ((WP7.ServiceReference.IInterpoolWP7)(this)).EndGetCurrentFamous(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCurrentFamousCompleted(object state) {
            if ((this.GetCurrentFamousCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCurrentFamousCompleted(this, new GetCurrentFamousCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCurrentFamousAsync(string userIdFacebook, int numClue) {
            this.GetCurrentFamousAsync(userIdFacebook, numClue, null);
        }
        
        public void GetCurrentFamousAsync(string userIdFacebook, int numClue, object userState) {
            if ((this.onBeginGetCurrentFamousDelegate == null)) {
                this.onBeginGetCurrentFamousDelegate = new BeginOperationDelegate(this.OnBeginGetCurrentFamous);
            }
            if ((this.onEndGetCurrentFamousDelegate == null)) {
                this.onEndGetCurrentFamousDelegate = new EndOperationDelegate(this.OnEndGetCurrentFamous);
            }
            if ((this.onGetCurrentFamousCompletedDelegate == null)) {
                this.onGetCurrentFamousCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCurrentFamousCompleted);
            }
            base.InvokeAsync(this.onBeginGetCurrentFamousDelegate, new object[] {
                        userIdFacebook,
                        numClue}, this.onEndGetCurrentFamousDelegate, this.onGetCurrentFamousCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7.ServiceReference.IInterpoolWP7.BeginFilterSuspects(string userIdFacebook, WP7.ServiceReference.DataFacebookUser fbud, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFilterSuspects(userIdFacebook, fbud, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WP7.ServiceReference.DataListFacebookUser WP7.ServiceReference.IInterpoolWP7.EndFilterSuspects(System.IAsyncResult result) {
            return base.Channel.EndFilterSuspects(result);
        }
        
        private System.IAsyncResult OnBeginFilterSuspects(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userIdFacebook = ((string)(inValues[0]));
            WP7.ServiceReference.DataFacebookUser fbud = ((WP7.ServiceReference.DataFacebookUser)(inValues[1]));
            return ((WP7.ServiceReference.IInterpoolWP7)(this)).BeginFilterSuspects(userIdFacebook, fbud, callback, asyncState);
        }
        
        private object[] OnEndFilterSuspects(System.IAsyncResult result) {
            WP7.ServiceReference.DataListFacebookUser retVal = ((WP7.ServiceReference.IInterpoolWP7)(this)).EndFilterSuspects(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFilterSuspectsCompleted(object state) {
            if ((this.FilterSuspectsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FilterSuspectsCompleted(this, new FilterSuspectsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FilterSuspectsAsync(string userIdFacebook, WP7.ServiceReference.DataFacebookUser fbud) {
            this.FilterSuspectsAsync(userIdFacebook, fbud, null);
        }
        
        public void FilterSuspectsAsync(string userIdFacebook, WP7.ServiceReference.DataFacebookUser fbud, object userState) {
            if ((this.onBeginFilterSuspectsDelegate == null)) {
                this.onBeginFilterSuspectsDelegate = new BeginOperationDelegate(this.OnBeginFilterSuspects);
            }
            if ((this.onEndFilterSuspectsDelegate == null)) {
                this.onEndFilterSuspectsDelegate = new EndOperationDelegate(this.OnEndFilterSuspects);
            }
            if ((this.onFilterSuspectsCompletedDelegate == null)) {
                this.onFilterSuspectsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFilterSuspectsCompleted);
            }
            base.InvokeAsync(this.onBeginFilterSuspectsDelegate, new object[] {
                        userIdFacebook,
                        fbud}, this.onEndFilterSuspectsDelegate, this.onFilterSuspectsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7.ServiceReference.IInterpoolWP7.BeginEmitOrderOfArrest(string userIdFacebook, string userIdFacebookSuspect, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEmitOrderOfArrest(userIdFacebook, userIdFacebookSuspect, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void WP7.ServiceReference.IInterpoolWP7.EndEmitOrderOfArrest(System.IAsyncResult result) {
            base.Channel.EndEmitOrderOfArrest(result);
        }
        
        private System.IAsyncResult OnBeginEmitOrderOfArrest(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userIdFacebook = ((string)(inValues[0]));
            string userIdFacebookSuspect = ((string)(inValues[1]));
            return ((WP7.ServiceReference.IInterpoolWP7)(this)).BeginEmitOrderOfArrest(userIdFacebook, userIdFacebookSuspect, callback, asyncState);
        }
        
        private object[] OnEndEmitOrderOfArrest(System.IAsyncResult result) {
            ((WP7.ServiceReference.IInterpoolWP7)(this)).EndEmitOrderOfArrest(result);
            return null;
        }
        
        private void OnEmitOrderOfArrestCompleted(object state) {
            if ((this.EmitOrderOfArrestCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EmitOrderOfArrestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EmitOrderOfArrestAsync(string userIdFacebook, string userIdFacebookSuspect) {
            this.EmitOrderOfArrestAsync(userIdFacebook, userIdFacebookSuspect, null);
        }
        
        public void EmitOrderOfArrestAsync(string userIdFacebook, string userIdFacebookSuspect, object userState) {
            if ((this.onBeginEmitOrderOfArrestDelegate == null)) {
                this.onBeginEmitOrderOfArrestDelegate = new BeginOperationDelegate(this.OnBeginEmitOrderOfArrest);
            }
            if ((this.onEndEmitOrderOfArrestDelegate == null)) {
                this.onEndEmitOrderOfArrestDelegate = new EndOperationDelegate(this.OnEndEmitOrderOfArrest);
            }
            if ((this.onEmitOrderOfArrestCompletedDelegate == null)) {
                this.onEmitOrderOfArrestCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEmitOrderOfArrestCompleted);
            }
            base.InvokeAsync(this.onBeginEmitOrderOfArrestDelegate, new object[] {
                        userIdFacebook,
                        userIdFacebookSuspect}, this.onEndEmitOrderOfArrestDelegate, this.onEmitOrderOfArrestCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7.ServiceReference.IInterpoolWP7.BeginGetCities(string userIdFacebook, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCities(userIdFacebook, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataCity> WP7.ServiceReference.IInterpoolWP7.EndGetCities(System.IAsyncResult result) {
            return base.Channel.EndGetCities(result);
        }
        
        private System.IAsyncResult OnBeginGetCities(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userIdFacebook = ((string)(inValues[0]));
            return ((WP7.ServiceReference.IInterpoolWP7)(this)).BeginGetCities(userIdFacebook, callback, asyncState);
        }
        
        private object[] OnEndGetCities(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataCity> retVal = ((WP7.ServiceReference.IInterpoolWP7)(this)).EndGetCities(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCitiesCompleted(object state) {
            if ((this.GetCitiesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCitiesCompleted(this, new GetCitiesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCitiesAsync(string userIdFacebook) {
            this.GetCitiesAsync(userIdFacebook, null);
        }
        
        public void GetCitiesAsync(string userIdFacebook, object userState) {
            if ((this.onBeginGetCitiesDelegate == null)) {
                this.onBeginGetCitiesDelegate = new BeginOperationDelegate(this.OnBeginGetCities);
            }
            if ((this.onEndGetCitiesDelegate == null)) {
                this.onEndGetCitiesDelegate = new EndOperationDelegate(this.OnEndGetCities);
            }
            if ((this.onGetCitiesCompletedDelegate == null)) {
                this.onGetCitiesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCitiesCompleted);
            }
            base.InvokeAsync(this.onBeginGetCitiesDelegate, new object[] {
                        userIdFacebook}, this.onEndGetCitiesDelegate, this.onGetCitiesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7.ServiceReference.IInterpoolWP7.BeginTravel(string userIdFacebook, string nameNextCity, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTravel(userIdFacebook, nameNextCity, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WP7.ServiceReference.DataCity WP7.ServiceReference.IInterpoolWP7.EndTravel(System.IAsyncResult result) {
            return base.Channel.EndTravel(result);
        }
        
        private System.IAsyncResult OnBeginTravel(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userIdFacebook = ((string)(inValues[0]));
            string nameNextCity = ((string)(inValues[1]));
            return ((WP7.ServiceReference.IInterpoolWP7)(this)).BeginTravel(userIdFacebook, nameNextCity, callback, asyncState);
        }
        
        private object[] OnEndTravel(System.IAsyncResult result) {
            WP7.ServiceReference.DataCity retVal = ((WP7.ServiceReference.IInterpoolWP7)(this)).EndTravel(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTravelCompleted(object state) {
            if ((this.TravelCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TravelCompleted(this, new TravelCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TravelAsync(string userIdFacebook, string nameNextCity) {
            this.TravelAsync(userIdFacebook, nameNextCity, null);
        }
        
        public void TravelAsync(string userIdFacebook, string nameNextCity, object userState) {
            if ((this.onBeginTravelDelegate == null)) {
                this.onBeginTravelDelegate = new BeginOperationDelegate(this.OnBeginTravel);
            }
            if ((this.onEndTravelDelegate == null)) {
                this.onEndTravelDelegate = new EndOperationDelegate(this.OnEndTravel);
            }
            if ((this.onTravelCompletedDelegate == null)) {
                this.onTravelCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTravelCompleted);
            }
            base.InvokeAsync(this.onBeginTravelDelegate, new object[] {
                        userIdFacebook,
                        nameNextCity}, this.onEndTravelDelegate, this.onTravelCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7.ServiceReference.IInterpoolWP7.BeginGetClueByFamous(string userIdFacebook, int numFamous, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetClueByFamous(userIdFacebook, numFamous, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WP7.ServiceReference.DataClue WP7.ServiceReference.IInterpoolWP7.EndGetClueByFamous(System.IAsyncResult result) {
            return base.Channel.EndGetClueByFamous(result);
        }
        
        private System.IAsyncResult OnBeginGetClueByFamous(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userIdFacebook = ((string)(inValues[0]));
            int numFamous = ((int)(inValues[1]));
            return ((WP7.ServiceReference.IInterpoolWP7)(this)).BeginGetClueByFamous(userIdFacebook, numFamous, callback, asyncState);
        }
        
        private object[] OnEndGetClueByFamous(System.IAsyncResult result) {
            WP7.ServiceReference.DataClue retVal = ((WP7.ServiceReference.IInterpoolWP7)(this)).EndGetClueByFamous(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetClueByFamousCompleted(object state) {
            if ((this.GetClueByFamousCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetClueByFamousCompleted(this, new GetClueByFamousCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetClueByFamousAsync(string userIdFacebook, int numFamous) {
            this.GetClueByFamousAsync(userIdFacebook, numFamous, null);
        }
        
        public void GetClueByFamousAsync(string userIdFacebook, int numFamous, object userState) {
            if ((this.onBeginGetClueByFamousDelegate == null)) {
                this.onBeginGetClueByFamousDelegate = new BeginOperationDelegate(this.OnBeginGetClueByFamous);
            }
            if ((this.onEndGetClueByFamousDelegate == null)) {
                this.onEndGetClueByFamousDelegate = new EndOperationDelegate(this.OnEndGetClueByFamous);
            }
            if ((this.onGetClueByFamousCompletedDelegate == null)) {
                this.onGetClueByFamousCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetClueByFamousCompleted);
            }
            base.InvokeAsync(this.onBeginGetClueByFamousDelegate, new object[] {
                        userIdFacebook,
                        numFamous}, this.onEndGetClueByFamousDelegate, this.onGetClueByFamousCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WP7.ServiceReference.IInterpoolWP7 CreateChannel() {
            return new InterpoolWP7ClientChannel(this);
        }
        
        private class InterpoolWP7ClientChannel : ChannelBase<WP7.ServiceReference.IInterpoolWP7>, WP7.ServiceReference.IInterpoolWP7 {
            
            public InterpoolWP7ClientChannel(System.ServiceModel.ClientBase<WP7.ServiceReference.IInterpoolWP7> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginStartGame(string userIdFacebook, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userIdFacebook;
                System.IAsyncResult _result = base.BeginInvoke("StartGame", _args, callback, asyncState);
                return _result;
            }
            
            public void EndStartGame(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("StartGame", _args, result);
            }
            
            public System.IAsyncResult BeginGetUserIdFacebook(string idLogin, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = idLogin;
                System.IAsyncResult _result = base.BeginInvoke("GetUserIdFacebook", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetUserIdFacebook(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetUserIdFacebook", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCurrentCity(string userIdFacebook, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userIdFacebook;
                System.IAsyncResult _result = base.BeginInvoke("GetCurrentCity", _args, callback, asyncState);
                return _result;
            }
            
            public WP7.ServiceReference.DataCity EndGetCurrentCity(System.IAsyncResult result) {
                object[] _args = new object[0];
                WP7.ServiceReference.DataCity _result = ((WP7.ServiceReference.DataCity)(base.EndInvoke("GetCurrentCity", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetPossibleCities(string userIdFacebook, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userIdFacebook;
                System.IAsyncResult _result = base.BeginInvoke("GetPossibleCities", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataCity> EndGetPossibleCities(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataCity> _result = ((System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataCity>)(base.EndInvoke("GetPossibleCities", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCurrentFamous(string userIdFacebook, int numClue, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = userIdFacebook;
                _args[1] = numClue;
                System.IAsyncResult _result = base.BeginInvoke("GetCurrentFamous", _args, callback, asyncState);
                return _result;
            }
            
            public WP7.ServiceReference.DataFamous EndGetCurrentFamous(System.IAsyncResult result) {
                object[] _args = new object[0];
                WP7.ServiceReference.DataFamous _result = ((WP7.ServiceReference.DataFamous)(base.EndInvoke("GetCurrentFamous", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginFilterSuspects(string userIdFacebook, WP7.ServiceReference.DataFacebookUser fbud, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = userIdFacebook;
                _args[1] = fbud;
                System.IAsyncResult _result = base.BeginInvoke("FilterSuspects", _args, callback, asyncState);
                return _result;
            }
            
            public WP7.ServiceReference.DataListFacebookUser EndFilterSuspects(System.IAsyncResult result) {
                object[] _args = new object[0];
                WP7.ServiceReference.DataListFacebookUser _result = ((WP7.ServiceReference.DataListFacebookUser)(base.EndInvoke("FilterSuspects", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginEmitOrderOfArrest(string userIdFacebook, string userIdFacebookSuspect, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = userIdFacebook;
                _args[1] = userIdFacebookSuspect;
                System.IAsyncResult _result = base.BeginInvoke("EmitOrderOfArrest", _args, callback, asyncState);
                return _result;
            }
            
            public void EndEmitOrderOfArrest(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("EmitOrderOfArrest", _args, result);
            }
            
            public System.IAsyncResult BeginGetCities(string userIdFacebook, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userIdFacebook;
                System.IAsyncResult _result = base.BeginInvoke("GetCities", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataCity> EndGetCities(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataCity> _result = ((System.Collections.ObjectModel.ObservableCollection<WP7.ServiceReference.DataCity>)(base.EndInvoke("GetCities", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginTravel(string userIdFacebook, string nameNextCity, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = userIdFacebook;
                _args[1] = nameNextCity;
                System.IAsyncResult _result = base.BeginInvoke("Travel", _args, callback, asyncState);
                return _result;
            }
            
            public WP7.ServiceReference.DataCity EndTravel(System.IAsyncResult result) {
                object[] _args = new object[0];
                WP7.ServiceReference.DataCity _result = ((WP7.ServiceReference.DataCity)(base.EndInvoke("Travel", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetClueByFamous(string userIdFacebook, int numFamous, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = userIdFacebook;
                _args[1] = numFamous;
                System.IAsyncResult _result = base.BeginInvoke("GetClueByFamous", _args, callback, asyncState);
                return _result;
            }
            
            public WP7.ServiceReference.DataClue EndGetClueByFamous(System.IAsyncResult result) {
                object[] _args = new object[0];
                WP7.ServiceReference.DataClue _result = ((WP7.ServiceReference.DataClue)(base.EndInvoke("GetClueByFamous", _args, result)));
                return _result;
            }
        }
    }
}
